# Generated by Django 3.1.5 on 2021-02-03 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_admin', '0004_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('company_address', models.TextField(max_length=200)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('project_summary', models.TextField(max_length=1000)),
                ('project_goal', models.TextField(max_length=1000)),
                ('project_impact', models.TextField(max_length=1000)),
                ('project_requirement', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('development_methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.development_methodology')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_details.projectdetail')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_details.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeaturePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_details.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDevelopmentTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fronted', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('server_side', models.CharField(max_length=100)),
                ('repository', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_details.projectdetail')),
            ],
        ),
    ]
