# Generated by Django 3.1.5 on 2021-02-03 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_details', '0003_projectfeatureservicecharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFeatureServiceCharge',
            new_name='ProjectServiceCharge',
        ),
    ]
