# Generated by Django 3.1.5 on 2021-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0006_timeline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline_user',
            name='update_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
