# Generated by Django 3.1.5 on 2021-02-04 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_details', '0007_auto_20210204_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline_user',
            name='profile_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline_user',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_details.projectdetail'),
        ),
    ]
