# Generated by Django 3.1.5 on 2021-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0008_auto_20210204_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline_user',
            name='profile_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeline_user',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
