# Generated by Django 3.1.5 on 2021-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0010_auto_20210204_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPaymentDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('profile_name', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('previous_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('due', models.CharField(blank=True, max_length=100, null=True)),
                ('new_payment', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
