# Generated by Django 3.1.5 on 2021-02-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0012_auto_20210204_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymentdone',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpaymentdone',
            name='due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpaymentdone',
            name='new_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpaymentdone',
            name='previous_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
