# Generated by Django 3.1.5 on 2021-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0013_auto_20210204_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymentdone',
            name='new_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
