# Generated by Django 3.1.5 on 2021-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0014_auto_20210204_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymentdone',
            name='previous_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
