# Generated by Django 3.1.5 on 2021-02-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0015_auto_20210206_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpaymentdone',
            name='new_payment',
        ),
    ]
