# Generated by Django 3.1.5 on 2021-02-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0017_projectmonthlypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmonthlypayment',
            name='month_name',
        ),
    ]
