# Generated by Django 3.1.5 on 2021-02-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0003_staffprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='group',
        ),
    ]
