# Generated by Django 3.1.5 on 2021-02-10 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_user', '0004_remove_staffprofile_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffProfile',
            new_name='Profile',
        ),
    ]
